# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

volesFullCpp <- function(nMon_, nSimul_, nBurn_, params_, nSteps_, T0_, randInit_, startVole_, startWeas_, addObsNoise_) {
    .Call('volesModel_volesFullCpp', PACKAGE = 'volesModel', nMon_, nSimul_, nBurn_, params_, nSteps_, T0_, randInit_, startVole_, startWeas_, addObsNoise_)
}

volesStdCpp <- function(nMon_, nSimul_, nBurn_, params_, nSteps_, T0_, randInit_, startVole_, startWeas_, addObsNoise_) {
    .Call('volesModel_volesStdCpp', PACKAGE = 'volesModel', nMon_, nSimul_, nBurn_, params_, nSteps_, T0_, randInit_, startVole_, startWeas_, addObsNoise_)
}

